Add a sensible error message if buildx not installed
Many of our .buildbot_dockerfile_* files use `docker buildx` as part of
the build process. If the host machine does not have this installed then
tryci jobs fail much later on with very strange error messages. We
should catch this early and make it clear what's going on.

diff --git a/tryci b/tryci
--- a/tryci
+++ b/tryci
@@ -20,6 +20,8 @@ CAP_ARGS="--cap-add CAP_PERFMON --cap-add SYS_PTRACE --security-opt seccomp=unco
 
 set -e
 
+error() { printf "\e[31m[ERROR]\e[0m %s\n" "$1" >&2; }
+
 run_image() {
     # Extract the dockerfile suffix. E.g. for '.buildbot_dockerfile_myrepo'
     # it's 'myimage'.
@@ -109,6 +111,12 @@ while [ $# -gt 0 ]; do
       ;;
   esac
 done
+
+if [ ! docker buildx version &>/dev/null ] && [ -z ${server} ]; then
+    error "Docker Buildx is not installed or not available in your PATH".
+    error "For installation instructions, visit: https://docs.docker.com/buildx/working-with-buildx/"
+    exit 1
+fi
 
 if [ ! -z ${server} ]; then
     export DOCKER_HOST="ssh://${server}"
